### ISSUE TITLE
Process for updating domain metadata

### ISSUE THREAD

**Issue by gbinal** [cisagov/dotgov-data#8]
What's the right method for suggesting or requesting an edit to the `agency` or `organization` field of the [domain](https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv) [exports](https://github.com/cisagov/dotgov-data/blob/main/current-full.csv)?  

In particular, there's two scenarios:  
* Simple normalizing.  In these cases, there's just some various in formatting or trivial naming differences that would be good to make consistent so that the data is cleaner.  Here's [two](https://github.com/cisagov/dotgov-data/blob/main/current-full.csv#L3980-L3982) [examples](https://github.com/cisagov/dotgov-data/blob/main/current-full.csv#L3963-L3964).  I would _think_ that these edits could be made without needing to bother the domain owner.  
* An `agency` or `organization` field is incorrect and should be changed.  There's some items where we'll come across mistakes in the data and it would be good to send in the corrected info and there be some means by which it can be run by the domain owner for an okay, and then updated.

**Comment by h-m-f-t** [comment]
Filing an issue about real or perceived errors works for us (folks can also email dotgov@cisa.dhs.gov). As you hinted, it's not as simple as modifying the domain data exports, but also can be done without poking the domain holder (unless necessary to verify).

I eyed your examples – can you say a bit more about the inconsistency? Your links were relative to the general file, not specific commits (and the underlying file was updated since last week), so it's possible we're not looking at the same domains you were, unfortunately.

**Comment by h-m-f-t** [comment]
@gbinal feel free to reopen this issue if needed.
